# Generated by Django 5.1.4 on 2025-01-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_nome_usuario_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='UID',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
